service:
  name: exposeless-build

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev # Set the default stage used. Default is dev
  region: eu-west-2 # Overwrite the default region used. Default is us-east-1
  memorySize: 1024 # Overwrite the default memory size. Default is 1024
  timeout: 60

functions:
  build:
    handler: build.build
